---
title: "GreatSchools Scrape"
author: "Enrico Manlapig"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(rvest)
library(RSelenium)
library(V8)
library(jsonlite)
library(stringr)
library(snakecase)
```


# School lists
```{r location_inputs}
state_name <- "california"

#city_name <- "santa barbara" # 5 pages
#city_name <- "goleta" # 2 pages
#city_name <- "summerland" # 1 page
#city_name <- "montecito" # 1 page
#city_name <- "carpinteria" # 1 page
#city_name <- "ojai" # 2 pages
#city_name <- "ventura" # 4 page
#city_name <- "santa-ynez" # 1 page
#city_name <- "solvang" # 1 pages
city_name <- "buellton" # 1 pages
```


```{r create_school_list_urls}
city_name <- gsub(" ", "-", city_name)

school_list_url_left <- paste0("https://www.greatschools.org/",
                              state_name,
                              "/",
                              city_name,
                              "/schools/?page=",
                              sep = "")

#school_list_url_left <- "https://www.greatschools.org/california/santa-barbara/schools/?page="

school_list_url_right <- "&view=table"

school_list_js_xpath <- "/html/head/script[1]"
```

# Scrape school lists
```{r scrape_school_lists}
num_pages_to_scrape <- 1 # Check this by visiting the city page

source("scrape_school_lists.R")


```



```{r construct_review_page_urls}
school_url_left <- 'https://www.greatschools.org'

v_school_url_right <- df_schools$reviews

v_school_url_right <- gsub("#Reviews", "reviews/", v_school_url_right)

v_school_urls <- paste0(school_url_left, v_school_url_right)

v_school_urls <- setdiff(v_school_urls[df_schools$num_reviews > 0], NA)


#school_url <- 'https://www.greatschools.org/california/santa-barbara/11279-Crane-Country-Day-School/reviews/'
```


```{r open_selenium_browser, message=FALSE}
#rD <- rsDriver()
rD <- rsDriver(browser = "firefox")
#remDr <- remoteDriver(browserName = 'firefox')
remDr <- rD[["client"]]
#Sys.sleep(5)
#remDr$open()
remDr$setWindowSize(width = 1920 / 2, height = 1080)
```


```{r loop_extract_school_reviews}
for (s in 1:length(v_school_urls)) {
  
  school_url <- v_school_urls[s]
  #school_url <- 'https://www.greatschools.org/california/santa-barbara/11279-Crane-Country-Day-School/reviews/'

  print(paste("Scraping: ", school_url))
    
  source("scrape_school_reviews.R")
  
  if (s == 1) {

    df_all_school_reviews <- df_school_review
  } else{
    df_all_school_reviews <- bind_rows(df_all_school_reviews,
                                       df_school_review)
  }
  Sys.sleep(5)
}
```

```{r close_selenium_browser}
remDr$close()
rD$server$stop()
rm(rD)
#system("taskkill /im java.exe /f", intern=FALSE, ignore.stdout=FALSE)
```


```{r saving}
data_path <- "../data/"

school_list_outfile <- paste0(city_name, "_list.RData", sep = "")
save(df_schools, file = paste(data_path, school_list_outfile, sep = ""))

school_reviews_outfile <- paste(city_name, "_reviews.RData", sep = "")
save(df_all_school_reviews, file = paste(data_path, school_reviews_outfile, sep = ""))
```

